### PR TITLE
Fixed bugs after my latest update.

### PR DESCRIPTION
**Pull request by ToxicDonut95**
I am sorry for these two updates so close to each other. Fixed bugs I created after my latest update..

### CODE REVIEW

**Comment by Laoujin** [comment]
And deployed... :)

**Comment by ToxicDonut95** [comment]
Thanks! :D

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ToxicDonut95** [comment]
Hi there,

Added a new update fixing some bugs I found while using sangu and changed the way you did the tagging on the village overview cause it was a bit buggy with the max of 5 request per second. 😝

I’m not an expert with GIT so I’m not 100% sure my commit went flawlessly so if there is any problem hmu. :D

I know sangu is free for everyone to use but just to be certain, the rules on TW.NL are changing and all scripts need to be re-examined. I would like  to do that for sangu so I could help people with fixing bugs or any request for the script to be changed in the meantime for as long as I’m active on TW. Since I haven’t made the script I would like to know if you are ok with that? 😃

Kind regards,

Jens

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Laoujin** [comment]
Hey,

I stopped playing a few years ago so it'd be cool if someone were to take over to maintain it.

**Pull request merged**
